In [3]:
import numpy as np

### 1d-arrey 

In [7]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a.ndim , a.shape, a.size,a.sum(),a.dtype

(1, (4,), 4, 10, dtype('int32'))

### changing types 

In [93]:
a=np.array([1,4,9,0,-7.0],dtype=np.int32)
a

array([ 1,  4,  9,  0, -7])

In [102]:
a.astype(np.float64)


array([ 1.,  4.,  9.,  0., -7.])

### nd_array


In [45]:
lst=[[1,2],[3,4],(9,5),(8,5,)]
b=np.array(lst,dtype=np.float64)
b

array([[1., 2.],
       [3., 4.],
       [9., 5.],
       [8., 5.]])

In [47]:
b.ndim ,b.shape ,b.size

(2, (4, 2), 8)

### create numpy by functions 

In [59]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [60]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [57]:
m+n

array([[3.36109123e+160, 2.31461371e-152],
       [5.46519796e+241, 1.02189324e-152]])

In [63]:
# divide distance(0-10) into 5 parts
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [67]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [85]:
np.random.binomial(n=2,p=.5,size=(5,2))

array([[1, 1],
       [1, 2],
       [0, 2],
       [1, 1],
       [1, 2]])

### staking

In [88]:
a=np.random.standard_normal((2,3))
b=np.random.standard_normal((2,3))
c=np.ones((2,3))

In [89]:
np.vstack((a,b,c))

array([[ 0.76483698,  0.73853363, -0.28667984],
       [ 0.38591736,  0.34903553, -0.97739957],
       [-0.99310894, -1.2434124 ,  0.98218474],
       [-0.55903279, -0.04472758, -1.57163508],
       [ 1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ]])

In [91]:
np.hstack((a,c))

array([[ 0.76483698,  0.73853363, -0.28667984,  1.        ,  1.        ,
         1.        ],
       [ 0.38591736,  0.34903553, -0.97739957,  1.        ,  1.        ,
         1.        ]])

In [99]:
c,c.transpose()

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

### another wy to goin array

In [6]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6, 9], [7, 8, 0]])

arr = np.concatenate((arr1, arr2), axis=1)
asr = np.hstack((arr1,arr2))

print(arr,"\n",asr)

[[1 2 5 6 9]
 [3 4 7 8 0]] 
 [[1 2 5 6 9]
 [3 4 7 8 0]]


### dummy aray  
avoid them.a=a.T

In [4]:
a = np.array([1, 2, 3, 4])
a.shape, a

((4,), array([1, 2, 3, 4]))

In [5]:
b=a.T

In [6]:
np.all(a==b),a,b

(True, array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [18]:
a=np.array([[1,2]])
a, a.shape

(array([[1, 2]]), (1, 2))

In [21]:
b=a.T
b.shape , b

((2, 1),
 array([[1],
        [2]]))

In [20]:
a-b

array([[ 0,  1],
       [-1,  0]])

In [146]:
np.all(a==b)

False

### save & load


In [156]:
np.save('a.npy',a)

In [157]:
a=np.load('a.npy')

In [158]:
a

array([[1, 2]])

### braodcasting

In [7]:
a=np.linspace(0,10,5)

In [8]:
a+1

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [9]:
b=np.ones((4,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
c = np.random.random((4,1))
c

array([[0.35464807],
       [0.86261146],
       [0.66230407],
       [0.02264199]])

In [11]:
a,b,a+b,b + c

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[ 1. ,  3.5,  6. ,  8.5, 11. ],
        [ 1. ,  3.5,  6. ,  8.5, 11. ],
        [ 1. ,  3.5,  6. ,  8.5, 11. ],
        [ 1. ,  3.5,  6. ,  8.5, 11. ]]),
 array([[1.35464807, 1.35464807, 1.35464807, 1.35464807, 1.35464807],
        [1.86261146, 1.86261146, 1.86261146, 1.86261146, 1.86261146],
        [1.66230407, 1.66230407, 1.66230407, 1.66230407, 1.66230407],
        [1.02264199, 1.02264199, 1.02264199, 1.02264199, 1.02264199]]))

In [49]:
#اگر در دوبعد مختلف 1 باشند بوردکست جواب میده.
a = np.array([[1,1,1,1],[1,1,1,1]])
b = np.array([[2],[2]])
a,b,a+b

(array([[1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[2],
        [2]]),
 array([[3, 3, 3, 3],
        [3, 3, 3, 3]]))

In [40]:
np.random.seed(1111)
A = np.random.randint(low = 1, high = 10, size = (3, 1, 4))
B = np.random.randint(low = 1, high = 10, size = (2, 1))
A,B,A+B

(array([[[8, 6, 2, 3]],
 
        [[5, 9, 7, 5]],
 
        [[9, 7, 3, 7]]]),
 array([[9],
        [4]]),
 array([[[17, 15, 11, 12],
         [12, 10,  6,  7]],
 
        [[14, 18, 16, 14],
         [ 9, 13, 11,  9]],
 
        [[18, 16, 12, 16],
         [13, 11,  7, 11]]]))

###  speed (numpy  >>>>  list)

In [218]:
x=np.linspace(0,100,100000)
%timeit np.sin(x)

611 µs ± 14.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [220]:
 %timeit [math.sin(i) for i in x]

13.6 ms ± 364 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [222]:
def get_lst(x):
    lst = []
    for i in x:
        lst.append(math.sin(i))
    return lst

%timeit get_lst(x)

17.4 ms ± 450 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [221]:
13.6/.611

22.25859247135843

In [223]:
17.4/.611

28.47790507364975

### slicing

In [9]:
#exactly the same as another
v=np.random.randint(0,2,(2,10))
v

array([[1, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 0, 0]])

In [16]:
v[:,::2]

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0]])

In [17]:
v[1,0]

0

In [20]:
v[1,[1,3,9]]

array([1, 0, 0])

In [53]:
a=v[[0]]
b=v[0]  
c=v[0,None]
for i in[a,b,c]:
    print(i.shape)


(1, 10)
(10,)
(1, 10)


### imutabel

In [61]:
v=np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
v1=v
v1[1]=0
print(f"""v1:{v1}
v:{v}""")

v1:[ 0.   0.   5.   7.5 10. ]
v:[ 0.   0.   5.   7.5 10. ]


In [38]:
v2=v.copy()
v2[2]=00
print(f"""v2:{v2}
v:{v}""")

v2:[ 0.   0.   0.   7.5 10. ]
v:[ 0.   0.   5.   7.5 10. ]


### boolian mask 

In [71]:
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [72]:
c=np.vstack((v,v))
c

array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ]])

In [73]:
bool_index= c>6
bool_index

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True]])

In [74]:
c[bool_index]

array([ 7.5, 10. ,  7.5, 10. ])

In [6]:
vv=np.random.randint(0,100,(10,10))
vv

array([[21, 18, 70, 14, 42, 85, 10,  4,  8, 77],
       [53, 19,  9, 51, 15, 66, 15, 42, 50, 65],
       [23, 77, 46, 62, 49, 97, 61, 90, 79, 49],
       [38, 60, 95, 82, 25, 99, 21, 66,  7, 50],
       [81, 92, 38, 42, 86, 45, 60, 30, 63, 37],
       [57, 70, 36, 40,  3, 26, 86, 63, 77, 73],
       [16, 72, 96, 96, 19, 56, 69, 86, 22, 38],
       [90, 59, 76, 81, 87, 55, 42, 27, 48, 50],
       [14,  2, 41, 29, 67, 73, 89, 85, 12, 60],
       [52, 59, 54, 53, 44, 47, 61, 86, 85, 31]])

In [56]:
vv[vv>50]=0
vv

array([[33, 36,  0,  0,  0, 32,  0, 13,  0, 49],
       [ 0,  0,  0,  0,  0,  0, 34, 24, 17, 21],
       [44,  4,  0, 24,  0, 27, 13, 16,  0,  0],
       [12, 28,  0,  0,  0, 35,  0, 24,  8,  0],
       [ 0, 35,  0, 45, 24, 30,  0,  0,  0,  0],
       [20, 44,  0, 36, 33,  0,  9,  0,  0,  0],
       [47, 48, 36, 33, 28,  0, 18, 49,  0, 48],
       [23, 25,  0, 14, 32,  0,  0,  0,  0, 24],
       [ 0, 33,  0,  0, 21,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 37,  0,  0, 43, 10,  0,  0]])

In [65]:
vv[1,0:5]=[100,100,100,100,100]
vv

array([[ 33,  36,   0,   0,   0,  32,   0,  13,   0,  49],
       [100, 100, 100, 100, 100,   0,  34,  24,  17,  21],
       [ 44,   4,   0,  24,   0,  27,  13,  16,   0,   0],
       [ 12,  28,   0,   0,   0,  35,   0,  24,   8,   0],
       [  0,  35,   0,  45,  24,  30,   0,   0,   0,   0],
       [ 20,  44,   0,  36,  33,   0,   9,   0,   0,   0],
       [ 47,  48,  36,  33,  28,   0,  18,  49,   0,  48],
       [ 23,  25,   0,  14,  32,   0,   0,   0,   0,  24],
       [  0,  33,   0,   0,  21,   0,   0,   0,   0,   0],
       [  0,   0,   0,  37,   0,   0,  43,  10,   0,   0]])

In [7]:
vv[9,[0,1,2]]=[10,10,10]
vv

array([[21, 18, 70, 14, 42, 85, 10,  4,  8, 77],
       [53, 19,  9, 51, 15, 66, 15, 42, 50, 65],
       [23, 77, 46, 62, 49, 97, 61, 90, 79, 49],
       [38, 60, 95, 82, 25, 99, 21, 66,  7, 50],
       [81, 92, 38, 42, 86, 45, 60, 30, 63, 37],
       [57, 70, 36, 40,  3, 26, 86, 63, 77, 73],
       [16, 72, 96, 96, 19, 56, 69, 86, 22, 38],
       [90, 59, 76, 81, 87, 55, 42, 27, 48, 50],
       [14,  2, 41, 29, 67, 73, 89, 85, 12, 60],
       [10, 10, 10, 53, 44, 47, 61, 86, 85, 31]])

In [8]:
vv[::2,0]

array([21, 23, 81, 16, 14])

In [57]:
foo = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])
r13 = np.array([True, False, True])
c23 = np.array([False, True, True])
foo[r13]

array([[3, 9, 7],
       [3, 3, 1]])

### reshape 

In [11]:
ax=np.random.standard_normal((4,3))
ax

array([[-0.0678532 , -0.05606998, -1.81818461],
       [-1.43619182, -0.17279872, -0.23527168],
       [-0.53596642,  0.02237324,  1.04526797],
       [ 0.05705313,  0.43029837,  0.8915177 ]])

In [14]:
ax.reshape(6,-1)
ax

array([[-0.0678532 , -0.05606998, -1.81818461],
       [-1.43619182, -0.17279872, -0.23527168],
       [-0.53596642,  0.02237324,  1.04526797],
       [ 0.05705313,  0.43029837,  0.8915177 ]])

### dot 

In [31]:
a=np.array([[1,2],[2,3]])
b=np.array([[2,2],[2,2]])
a,b

(array([[1, 2],
        [2, 3]]),
 array([[2, 2],
        [2, 2]]))

In [32]:
np.dot(a,b)

array([[ 6,  6],
       [10, 10]])

In [33]:
a@b

array([[ 6,  6],
       [10, 10]])

In [38]:
#dumpy in dot()
a=np.array([1,2,3])
b=np.array([1,1,2])
a,b,np.dot(a,b),np.dot(2,[3,7]),np.dot([3,5],[9,0]),a@b

(array([1, 2, 3]), array([1, 1, 2]), 9, array([ 6, 14]), 27, 9)

#### dot ex
((A'PA)^-1)(A'PL)

In [9]:
A = np.array([[1,2],[3,5],[7,6]])
P = np.diag([5,5,5])
L = np.array([7,3, 2]).reshape((3,1))

### where

In [14]:
array = np.array([1,2,3,4])
rows = np.where(array >= 2.5)
rows2 = np.where(array >= 2.5,"5>",0)
rows# return index tuple 
array[rows],rows,rows2,


(array([3, 4]),
 (array([2, 3], dtype=int64),),
 array(['0', '0', '5>', '5>'], dtype='<U11'))

In [76]:
t = np.array([[1,2,3,'bar'],
 [2,"bar",3,4,],
 [5,6,7,'hello'],
 [8,9,1,'bar']])


t

array([['1', '2', '3', 'bar'],
       ['2', 'bar', '3', '4'],
       ['5', '6', '7', 'hello'],
       ['8', '9', '1', 'bar']], dtype='<U11')

In [77]:
rows,cols=np.where(t=="bar")
np.where(t=="bar")

(array([0, 1, 3], dtype=int64), array([3, 1, 3], dtype=int64))

In [28]:
t[:,cols]

array([['bar', '2', 'bar'],
       ['4', 'bar', '4'],
       ['hello', '6', 'hello'],
       ['bar', '9', 'bar']], dtype='<U11')

In [29]:
t[rows],t[cols],t[rows,cols]

(array([['1', '2', '3', 'bar'],
        ['2', 'bar', '3', '4'],
        ['8', '9', '1', 'bar']], dtype='<U11'),
 array([['8', '9', '1', 'bar'],
        ['2', 'bar', '3', '4'],
        ['8', '9', '1', 'bar']], dtype='<U11'),
 array(['bar', 'bar', 'bar'], dtype='<U11'))

In [30]:
rows,cols

(array([0, 1, 3], dtype=int64), array([3, 1, 3], dtype=int64))

### split

In [19]:
# to n group
a = np.arange(10)
np.split(a,5)

# till this arg
a = np.arange(10)
np.split(a,[4,6,8,9])

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7]), array([8]), array([9])]

### delet an colum
or whith slicing

In [6]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
a_del = np.delete( a, 3, 0)
a_del

array([[0, 1],
       [2, 3],
       [4, 5],
       [8, 9]])

In [10]:
a_del2 = np.delete( a, 0, 1)
a_del2

array([[1],
       [3],
       [5],
       [7],
       [9]])

### nonezeros

In [22]:
# mine work : seprate elements witch has mine Condition

In [24]:
a = np.random.randint(0,11,(5,5))
a

array([[ 5,  0,  7,  9,  4],
       [ 5,  9, 10,  1, 10],
       [ 0,  2,  5, 10,  0],
       [ 1,  1,  8,  9,  8],
       [ 3,  0,  6,  2,  9]])

In [25]:
a>5

array([[False, False,  True,  True, False],
       [False,  True,  True, False,  True],
       [False, False, False,  True, False],
       [False, False,  True,  True,  True],
       [False, False,  True, False,  True]])

In [26]:
(a>5).nonzero()

(array([0, 0, 1, 1, 1, 2, 3, 3, 3, 4, 4], dtype=int64),
 array([2, 3, 1, 2, 4, 3, 2, 3, 4, 2, 4], dtype=int64))

In [27]:
a[(a>5).nonzero()]

array([ 7,  9,  9, 10, 10, 10,  8,  9,  8,  6,  9])

In [28]:
# important: input : array --> outpout " tuple
# use [0] to make it into array

In [37]:
(a>5).nonzero(),type((a>5).nonzero()),type((a>5).nonzero()[1])

((array([0, 0, 1, 1, 1, 2, 3, 3, 3, 4, 4], dtype=int64),
  array([2, 3, 1, 2, 4, 3, 2, 3, 4, 2, 4], dtype=int64)),
 tuple,
 numpy.ndarray)

###  choice

In [31]:
# making 20 random number from(0,100) without repeat repeating numbers
place = np.random.choice(100, 20, replace = False)
place

array([25, 48,  7, 81, 46, 44, 45, 87, 37, 82, 70, 88, 92, 83, 52, 65, 35,
       98, 21, 22])

### mask 

In [78]:
foo = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])

In [82]:
mask = foo==3
mask,mask.shape

(array([[ True, False, False],
        [False, False,  True],
        [ True,  True, False]]),
 (3, 3))

In [83]:
foo[mask]

array([3, 3, 3, 3])

In [84]:
r13 = np.array([True, False, True])
c23 = np.array([False, True, True])
foo[r13]

array([[3, 9, 7],
       [3, 3, 1]])

In [92]:
#==foo[[0, 2], [1, 2]]
foo[r13,c23]


array([9, 1])

In [87]:
~np.array([False, True])

array([ True, False])

### nan 

In [ ]:
#nan is float.we cant use nan in int<str,or bool array


In [104]:
bot = np.ones(shape = (3, 4),dtype=np.int32)
print(bot.dtype)
boot = bot.astype(np.float32)
bot,boot

int32


(array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [108]:
boot[[1,1],[0,3]] = np.nan
boot

array([[ 1.,  1.,  1.,  1.],
       [nan,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

In [109]:
bot[[1,1],[0,3]] = np.nan

ValueError: cannot convert float NaN to integer

In [113]:
# we use isnon not this stracture
boot == np.nan,boot != np.nan

(array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]))

In [115]:
np.isnan(boot)

array([[False, False, False, False],
       [ True, False, False,  True],
       [False, False, False, False]])

In [117]:
lot = np.ones(shape = (3, 4))
(boot + lot)*2

array([[ 4.,  4.,  4.,  4.],
       [nan,  4.,  4., nan],
       [ 4.,  4.,  4.,  4.]])

### Infinity and -Infinity

In [119]:
np.array([np.inf,2,np.NINF])

array([ inf,   2., -inf])

In [120]:
np.array([-1, 1])/0

C:\Users\user\AppData\Local\Temp\ipykernel_13120\1566236623.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([-1, 1])/0


array([-inf,  inf])

### random 

In [127]:
generator = np.random.default_rng(seed = 123)


In [130]:
#Sample integers in range with replacement
a = generator.integers(0,100,(2,5))
a

array([[ 2, 51, 26, 24, 24],
       [82, 79, 21, 40, 74]], dtype=int64)

In [140]:
generator.choice(10,(10),replace = False)

array([7, 8, 3, 6, 4, 2, 1, 9, 5, 0], dtype=int64)

In [186]:
# shaffel in row and cloumn
foo = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]])
a = generator.permutation(foo,1)
a,foo

(array([[ 2,  1],
        [ 4,  3],
        [ 6,  5],
        [ 8,  7],
        [10,  9]]),
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]))

In [185]:
#shuffel


In [183]:
#تفائت اینه که شافل تابع اصلی رو تغییر میده ولی اونیکی کپی میگیره و اصلی رو تغییر نمیده
arr = np.arange(10)
generator.shuffle(arr) , arr

(None, array([0, 4, 6, 9, 5, 7, 2, 8, 1, 3]))

In [172]:
# چندبعدی ها اعداد داخل جابه جا نمیشن
arr = np.arange(9).reshape((3, 3))
np.random.shuffle(arr)
arr

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])