### sum 

In [1]:
import numpy as np

In [3]:
foo = np.array(
    [[5.0, 2.0, 9.0],
     [1.0, 0.0, 2.0],
     [1.0, 7.0, 8.0]]
)

In [4]:
np.sum(foo)

35.0

In [5]:
np.sum(foo,0)

array([ 7.,  9., 19.])

In [7]:
np.sum(foo,1)

array([16.,  3., 16.])

In [8]:
foo[1,1] = np.nan
np.sum(foo)

nan

In [17]:
#3 ways to fix this problem
q = np.sum(foo,where = ~np.isnan(foo))

nan_to_nan_foo = np.nan_to_num(foo)
q2 = np.sum(nan_to_nan_foo)

q3 = np.nansum(foo)

q , q2 , q3 ,nan_to_nan_foo

(35.0,
 35.0,
 35.0,
 array([[5., 2., 9.],
        [1., 0., 2.],
        [1., 7., 8.]]))

###  all

In [18]:
foo = np.array([
    [np.nan,    4.4],
    [   1.0,    3.2],
    [np.nan, np.nan],
    [   0.1, np.nan]
])

In [22]:
np.all(np.isnan(foo))

False

In [26]:
np.all(np.isnan(foo),0)

array([False, False])

In [27]:
np.all(np.isnan(foo),1)

array([False, False,  True, False])

### any 

In [28]:
np.any(np.isnan(foo))

True

In [30]:
np.any(np.isnan(foo), axis=0)

array([ True,  True])

In [29]:
np.any(np.isnan(foo), axis=1)

array([ True, False,  True,  True])

### concatenate 

In [39]:
foo = np.array([1, 1])
bar = np.array([2, 2])
baz = np.array([[1, 1]])
bingo = np.array([[2, 2, 2]])


In [47]:
np.concatenate((baz,bingo),1)


array([[1, 1, 2, 2, 2]])

In [45]:
np.concatenate((foo,bar),).shape

(4,)

In [49]:
a = np.arange(6).reshape(2,3)

### count elements

In [10]:
county = np.arange(12).reshape((3,4))
county

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np.count_nonzero((county%2 ==0 )| (county<3))

7

In [12]:
# or sum.but sum is slower
np.sum((county%2 ==0 )| (county<3))

7

In [31]:
# nan and inf
county = county.astype(np.float32())
county[[0,1],0] = np.nan
np.count_nonzero(np.isnan(county))

2