In [2]:
import numpy as np

In [15]:
Z = np.zeros((10,10))
"%d bytes" % (Z.size * Z.itemsize)

'800 bytes'

In [19]:
z=np.arange(30,1,-1)


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
x=np.zeros((10,10))
x[:,[0,9]]=1
x[[0,9],:]=1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
# add a border
c=np.random.random_integers(0,100,size=(2,2))
lst=range(0,13)
c=np.pad(c,1,mode='constant',)
c

C:\Users\user\AppData\Local\Temp\ipykernel_16312\2302938440.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  c=np.random.random_integers(0,100,size=(2,2))


array([[ 0,  0,  0,  0],
       [ 0,  6,  6,  0],
       [ 0, 97,  6,  0],
       [ 0,  0,  0,  0]])

In [61]:
c[np.nonzero(c)]

array([ 6,  6, 97,  6])

In [ ]:
np.hstack