the source of question is here:<br>
[website](https://www.practiceprobs.com/problemsets/python-numpy/)

In [1]:
import numpy as np

You’re a relationship scientist, and you’ve developed a questionnaire that determines a person’s love score - a real-valued number between 0 and 100. Your theory is that two people with similar love scores should make a good match 👩‍❤️‍💋‍👨

Given the love scores for 10 different people, create a 2-d array where (i,j) gives the absolute difference of the love scores for person i and person j.

In [14]:
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(low=0, high=100, size=10), 2)

print(love_scores)
# [ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]

[ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]


In [15]:
# two show more colum in print
np.set_printoptions(linewidth=999)

In [20]:
different = np.abs(love_scores.reshape(10,1) - love_scores.reshape(1,10))
different


array([[ 0.  , 44.08, 82.27, 88.65, 75.38, 65.11, 31.44, 46.99,  1.11, 55.19],
       [44.08,  0.  , 38.19, 44.57, 31.3 , 21.03, 12.64,  2.91, 45.19, 11.11],
       [82.27, 38.19,  0.  ,  6.38,  6.89, 17.16, 50.83, 35.28, 83.38, 27.08],
       [88.65, 44.57,  6.38,  0.  , 13.27, 23.54, 57.21, 41.66, 89.76, 33.46],
       [75.38, 31.3 ,  6.89, 13.27,  0.  , 10.27, 43.94, 28.39, 76.49, 20.19],
       [65.11, 21.03, 17.16, 23.54, 10.27,  0.  , 33.67, 18.12, 66.22,  9.92],
       [31.44, 12.64, 50.83, 57.21, 43.94, 33.67,  0.  , 15.55, 32.55, 23.75],
       [46.99,  2.91, 35.28, 41.66, 28.39, 18.12, 15.55,  0.  , 48.1 ,  8.2 ],
       [ 1.11, 45.19, 83.38, 89.76, 76.49, 66.22, 32.55, 48.1 ,  0.  , 56.3 ],
       [55.19, 11.11, 27.08, 33.46, 20.19,  9.92, 23.75,  8.2 , 56.3 ,  0.  ]])

You’re a vindictive professor 👨‍🏫 and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide to give zeros to the first three students who score less than sixty, in the order they turned in their exams.

Given a 1-d array of integers, identify the first three values less than sixty and replace them with zero.

main trick is nonzeros

In [2]:
import numpy as np
generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))
print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [3]:
scores[(scores<60).nonzero()[0][:3]]=0
scores

array([68.,  0., 76.,  0.,  0., 54., 63., 64., 36., 88., 80., 82., 84.,
       76., 42.])

ex.3<br>
Eager to make your mark on the PTA, you decide the best way to hide eggs for the upcoming Easter egg hunt is to use NumPy
. You represent the field as a 10x10 array of 0s.
Insert 20 random normal values at random (non repeating) locations in the grid. Then you'll know how much candy to hide at each spot.

In [2]:
import numpy as np

field = np.zeros(shape = (10, 10))

print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
candy_amount = np.round(np.random.normal(size=20) ,2)
candy_amount

array([-1.78,  0.81,  0.33,  0.22, -0.14, -1.36,  0.05, -0.41, -0.19,
       -1.47,  1.17, -0.43,  0.29, -0.42,  0.31,  1.31, -1.16,  0.1 ,
        0.85, -0.58])

In [4]:
place = np.random.choice(field.size,20,replace = False)
np.sort(place)

array([ 3,  4, 11, 14, 38, 41, 42, 51, 54, 55, 60, 63, 68, 76, 80, 83, 85,
       93, 97, 98])

In [10]:
np.set_printoptions(linewidth=1000)
field.reshape(100,)[[place]] = [candy_amount]
field

array([[ 0.  ,  0.  ,  0.  , -0.19, -0.43,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.05,  0.  ,  0.  , -0.14,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.85,  0.  ],
       [ 0.  ,  1.31,  0.1 ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.22,  0.  ,  0.  , -1.36, -1.47,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.41,  0.  ,  0.  , -0.42,  0.  ,  0.  ,  0.  ,  0.  ,  0.81,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.29,  0.  ,  0.  ,  0.  ],
       [-1.78,  0.  ,  0.  , -0.58,  0.  , -1.16,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.17,  0.  ,  0.  ,  0.  ,  0.31,  0.33,  0.  ]])

In [7]:
np.set_printoptions(linewidth=1000)

#reval underestands number of array
field.ravel()[[place]] = [candy_amount]
field

array([[ 0.  ,  0.  ,  0.  , -0.19, -0.43,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.05,  0.  ,  0.  , -0.14,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.85,  0.  ],
       [ 0.  ,  1.31,  0.1 ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.22,  0.  ,  0.  , -1.36, -1.47,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.41,  0.  ,  0.  , -0.42,  0.  ,  0.  ,  0.  ,  0.  ,  0.81,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.29,  0.  ,  0.  ,  0.  ],
       [-1.78,  0.  ,  0.  , -0.58,  0.  , -1.16,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.17,  0.  ,  0.  ,  0.  ,  0.31,  0.33,  0.  ]])